export default [
  {
    id: 1,
    title: "Methi Paratha",
    price: 800.0,
    img: "https://www.harvestfoodindustries.com/img/Whole-Wheat-Paratha-sm.jpg",
    quantity: 1,
  },
  {
    id: 2,
    title: "Paratha ",
    price: 100.0,
    img: "https://www.harvestfoodindustries.com/img/Plain-Paratha-jumbo-pack-sm.jpg",
    quantity: 1,
  },
  {
    id: 3,
    title: "WHOLE WHEAT NAAN",
    price: 500.0,
    img: "https://www.harvestfoodindustries.com/img/Whole-Wheat-Naan-sm.jpg",
    quantity: 1,
  },
  {
    id: 4,
    title: "Aaloo (Potato) Paratha",
    price: 300.0,
    img: "https://www.harvestfoodindustries.com/img/Aloo-Paratha-sm.jpg",
    quantity: 1,
  },
  {
    id: 5,
    title: "CRUNCHY ROLL",
    price: 500.0,
    img: "https://www.harvestfoodindustries.com/img/Crunchy-Roll-sm.jpg",
    quantity: 1,
  },
  {
    id: 6,
    title: "POTATO NUGGETS",
    price: 350.0,
    img: "https://www.harvestfoodindustries.com/img/Potato-Nuggets-sm.jpg",
    quantity: 1,
  },
  {
    id: 7,
    title: "CHAPATI",
    price: 200.0,
    img: "https://www.harvestfoodindustries.com/img/Chapati-sm.jpg",
    quantity: 1,
  },
  {
    id: 8,
    title: "TANDOORI NAAN",
    price: 600.0,
    img: "https://www.harvestfoodindustries.com/img/Naan-sm.jpg",
    quantity: 1,
  },
  {
    id: 9,
    title: "SHEERMAL",
    price: 350.0,
    img: "https://www.harvestfoodindustries.com/img/Sheermal-sm.jpg",
    quantity: 1,
  },
  {
    id: 10,
    title: "HOME STYLE PARATHA",
    price: 1000.0,
    img: "https://www.harvestfoodindustries.com/img/Home-Style-Paratha-sm.jpg",
    quantity: 1,
  },
  {
    id: 11,
    title: "VEGETABLE SAMOSA",
    price: 600.0,
    img: "https://www.harvestfoodindustries.com/img/Vegetable-Samosa-sm.jpg",
    quantity: 1,
  },
  {
    id: 12,
    title: "GAJAR HALWA",
    price: 500.0,
    img: "https://www.harvestfoodindustries.com/img/Gajar-Halwa-sm.jpg",
    quantity: 1,
  },
  {
    id: 13,
    title: "LOKI HALWA",
    price: 100.0,
    img: "https://www.harvestfoodindustries.com/img/Loki-Halwa-sm.jpg",
    quantity: 1,
  },
  {
    id: 14,
    title: "CHANA DAL HALWA",
    price: 500.0,
    img: "https://www.harvestfoodindustries.com/img/Chana-Dal-Halwa-sm.jpg",
    quantity: 1,
  },
];